# Generated by Django 3.0.7 on 2020-07-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('department', models.CharField(choices=[('1', 'Developer'), ('2', 'System Admin'), ('3', 'HR'), ('4', 'Data Analyst'), ('5', 'Finance')], max_length=20)),
                ('image', models.ImageField(max_length=255, upload_to='static/images/')),
            ],
        ),
    ]
