# Generated by Django 3.0.7 on 2020-07-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
